/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBar: typeof import('./src/components/ChatBar.vue')['default']
    LivePlayer: typeof import('./src/components/LivePlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopAppBar: typeof import('./src/components/TopAppBar.vue')['default']
  }
}
